# Generated by Django 4.0.5 on 2023-01-09 11:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=255, null=True)),
                ('is_staff', models.BooleanField(null=True)),
                ('is_superuser', models.BooleanField(null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('customer', 'klient'), ('employee', 'pracownik'), ('salon_owner', 'właścieciel salonu')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HairSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=5)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'HairSalons',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalonOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salon_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[("women's", 'Damskie'), ("men's", 'Meskie')], max_length=20)),
                ('describe', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')])),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('salonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')])),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('is_day_off', models.BooleanField(default=False, null=True)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.employee')),
            ],
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.salonowner'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salonId_reservation', to='booking.hairsalon')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceId_reservation', to='booking.service')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerId_reservation', to='booking.customer')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeId_reservation', to='booking.employee')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'unique_together': {('salonId', 'employeeId', 'date', 'start_time')},
            },
        ),
    ]
