# Generated by Django 4.0.5 on 2023-01-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='hairsalon',
            options={'ordering': ['id'], 'verbose_name_plural': 'HairSalons'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='salonowner',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workhours',
            options={'ordering': ['id']},
        ),
    ]
