# Generated by Django 4.0.5 on 2022-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='miejscowosc',
            field=models.CharField(max_length=100),
        ),
    ]
