# Generated by Django 4.0.5 on 2023-01-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_admin_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairsalon',
            name='post_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
