# Generated by Django 4.0.5 on 2022-06-30 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_user_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('miejscowosc', models.CharField(max_length=100, unique=True)),
                ('ulica', models.CharField(max_length=100, unique=True)),
                ('nr_budynku', models.CharField(max_length=5, unique=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=20, null=True)),
                ('poczta', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('wlasciciel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salony',
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_uslugi', models.CharField(choices=[('Fryzjerskie', 'Fryzjerskie'), ('Kosmetyczne', 'Kosmetyczne'), ('Barber', 'Barber')], max_length=20)),
                ('typ_uslugi', models.CharField(choices=[('Damskie', 'Damskie'), ('Meskie', 'Meskie')], max_length=20)),
                ('nazwa_uslugi', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField()),
                ('czas', models.IntegerField(default=0)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.salon')),
            ],
            options={
                'verbose_name_plural': 'Uslugi',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('godzina', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('do_kogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_reservation', to=settings.AUTH_USER_MODEL)),
                ('klientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reservation', to=settings.AUTH_USER_MODEL)),
                ('salonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.salon')),
                ('uslugaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.usluga')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
    ]
