# Generated by Django 4.0.5 on 2022-11-11 10:26

import booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_salon_miejscowosc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.salon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hours', models.TimeField(blank=True, null=True)),
                ('is_day_off', models.BooleanField(default=False, null=True)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalonOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salon_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
