# Generated by Django 4.0.5 on 2022-11-11 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_employee_workhours_salonowner_customer_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100, unique=True)),
                ('house_number', models.CharField(max_length=5, unique=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'HairSalons',
            },
        ),
        migrations.RemoveField(
            model_name='usluga',
            name='salonID',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[("women's", 'Damskie'), ("men's", 'Meskie')], max_length=20)),
                ('describe', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='salonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='uslugaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service'),
        ),
        migrations.AlterField(
            model_name='salonowner',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon'),
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.DeleteModel(
            name='Usluga',
        ),
    ]
