# Generated by Django 4.0.5 on 2022-11-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hairsalon_remove_usluga_salonid_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
