# Generated by Django 4.0.5 on 2022-11-11 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerId_reservation', to='booking.customer')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeId_reservation', to=settings.AUTH_USER_MODEL)),
                ('salonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salonId_reservation', to='booking.hairsalon')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceId_reservation', to='booking.service')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
