# Generated by Django 4.0.5 on 2022-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'klient'), ('employee', 'pracownik'), ('salon_owner', 'właścieciel salonu')], max_length=20),
        ),
    ]
