# Generated by Django 4.0.5 on 2022-11-11 14:34

import booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_admin_user_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='HairSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100, unique=True)),
                ('house_number', models.CharField(max_length=5, unique=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'HairSalons',
            },
        ),
        migrations.CreateModel(
            name='SalonOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salon_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hours', models.TimeField(blank=True, null=True)),
                ('is_day_off', models.BooleanField(default=False, null=True)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[("women's", 'Damskie'), ("men's", 'Meskie')], max_length=20)),
                ('describe', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerId_reservation', to='booking.customer')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeId_reservation', to='booking.employee')),
                ('salonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salonId_reservation', to='booking.hairsalon')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceId_reservation', to='booking.service')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.salonowner'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=booking.models.upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('salonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairsalon')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
    ]
