# Generated by Django 4.0.5 on 2022-11-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_customer_employee_hairsalon_salonowner_workhours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhours',
            old_name='to_hours',
            new_name='to_hour',
        ),
    ]
