# Generated by Django 4.0.5 on 2022-12-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_admin_customer_employee_hairsalon_salonowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
