# Generated by Django 4.0.5 on 2022-12-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_openinghours_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together=set(),
        ),
    ]
